default: &default
  protocol: 'http'
  host: db
  port: 5984
  username: admin
  password: password
  prefix: balua

development:
  <<: *default
  suffix: development

test:
  <<: *default
  suffix: test
