name: Ruby on Rails CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      couchdb:
        image: couchdb:3.4
        ports:
          - 5984:5984
        options: >-
          --health-cmd "curl -f http://localhost:5984/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      COUCHDB_HOST: localhost
      COUCHDB_PORT: 5984
      COUCHDB_USERNAME: admin
      COUCHDB_PASSWORD: password

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler-audit
        bundle install --jobs 4 --retry 3

    - name: Run security audit
      run: bundle exec bundler-audit check --update

    - name: Wait for CouchDB to be healthy
      run: |
        echo "Waiting for CouchDB..."
        for i in {1..10}; do
          curl -f http://$COUCHDB_USERNAME:$COUCHDB_PASSWORD@$COUCHDB_HOST:$COUCHDB_PORT/ && break
          sleep 5
        done

    - name: Set up Database
      run: |
        bin/rails db:create
        bin/rails db:schema:load

    - name: Run tests
      run: bundle exec rspec
